app = 'software-engineer-interview-bot'
primary_region = 'syd'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = '5175'

[http_service]
  internal_port = 5175
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1