
# fly.toml app configuration file generated for backend-frosty-tree-5260 on 2025-06-10T13:53:34+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-frosty-tree-5260'
primary_region = 'syd'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[processes]
web = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1